name: web_browser_detect
description: FlutterWeb browser detection package.
version: 1.0.1
homepage: https://github.com/tomaschyly/web_browser_detect
repository: https://github.com/tomaschyly/web_browser_detect
issue_tracker: https://github.com/tomaschyly/web_browser_detect/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  universal_html: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
